# Generated by Django 4.2.3 on 2023-07-05 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_conta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='essecial',
            new_name='essencial',
        ),
    ]
